from __future__ import annotations

import argparse
import random
import sys
import time
import webbrowser
from pathlib import Path

from .applicant import ApplicantProfile, load_profile
from .audit import write_audit_event
from .captcha import estimate_captcha_cost
from .crypto_profile import encrypt_profile_json, load_encrypted_profile, passphrase_from_env
from .deadline import parse_deadline, remaining_time_text
from .destinations import list_destination_keys, resolve_destinations
from .e2e import SelectorProfile, write_playwright_script
from .input_plan import build_input_plan
from .rehearsal import run_rehearsal
from .render import plan_summary_json, render_plan


def _add_profile_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--profile", help="Plain JSON profile path. Use local files only.")
    parser.add_argument("--encrypted-profile", help="Encrypted profile path generated by encrypt-profile.")
    parser.add_argument(
        "--passphrase-env",
        default="APPLICANT_PROFILE_PASSPHRASE",
        help="Environment variable containing the encrypted profile passphrase.",
    )


def _load_profile_from_args(args: argparse.Namespace) -> ApplicantProfile:
    if bool(args.profile) == bool(args.encrypted_profile):
        raise ValueError("Specify exactly one of --profile or --encrypted-profile")
    if args.encrypted_profile:
        return load_encrypted_profile(
            args.encrypted_profile,
            passphrase_from_env(args.passphrase_env),
        )
    return load_profile(args.profile)


def cmd_encrypt_profile(args: argparse.Namespace) -> int:
    passphrase = passphrase_from_env(args.passphrase_env)
    encrypt_profile_json(args.input_path, args.output_path, passphrase)
    print(f"Encrypted profile written to {args.output_path}")
    return 0


def cmd_plan(args: argparse.Namespace) -> int:
    profile = _load_profile_from_args(args)
    rng = random.Random(args.seed) if args.seed is not None else None
    deadline_text = remaining_time_text(parse_deadline(args.deadline)) if args.deadline else None
    for destination in resolve_destinations(args.location):
        plan = build_input_plan(profile, destination, rng=rng)
        print(render_plan(plan, remaining=deadline_text))
        print("\n---\n")
        if args.audit_log:
            write_audit_event(
                args.audit_log,
                {
                    "event": "plan",
                    "destination": destination.key,
                    "plan": plan.as_dict(),
                },
            )
    return 0


def cmd_open(args: argparse.Namespace) -> int:
    profile = _load_profile_from_args(args)
    destinations = resolve_destinations(args.location)
    rng = random.Random(args.seed) if args.seed is not None else None
    for index, destination in enumerate(destinations):
        plan = build_input_plan(profile, destination, rng=rng)
        print(render_plan(plan))
        print(f"Opening: {destination.url}")
        webbrowser.open(destination.url)
        if args.audit_log:
            write_audit_event(
                args.audit_log,
                {
                    "event": "open",
                    "destination": destination.key,
                    "url": destination.url,
                    "plan": plan.as_dict(),
                },
            )
        if index < len(destinations) - 1 and args.interval_seconds > 0:
            print(f"Waiting {args.interval_seconds} seconds before the next page...")
            time.sleep(args.interval_seconds)
    return 0


def cmd_captcha_cost(args: argparse.Namespace) -> int:
    estimate = estimate_captcha_cost(args.provider, args.expected_count, args.cost_per_1000)
    print(estimate.as_text())
    return 0


def cmd_e2e_script(args: argparse.Namespace) -> int:
    profile = _load_profile_from_args(args)
    destinations = resolve_destinations(args.location)
    if len(destinations) != 1:
        raise ValueError("e2e-script requires a single location, not all")
    selectors = SelectorProfile.from_file(args.selectors)
    rng = random.Random(args.seed) if args.seed is not None else None
    plan = build_input_plan(profile, destinations[0], rng=rng)
    write_playwright_script(
        output_path=args.out,
        plan=plan,
        selectors=selectors,
        url=args.url,
        submit=args.submit,
        min_delay_ms=args.min_delay_ms,
        max_delay_ms=args.max_delay_ms,
    )
    print(f"E2E script written to {args.out}")
    return 0


def cmd_rehearse(args: argparse.Namespace) -> int:
    profile = _load_profile_from_args(args)
    selectors = SelectorProfile.from_file(args.selectors)
    result = run_rehearsal(
        profile=profile,
        location=args.location,
        selectors=selectors,
        iterations=args.iterations,
        local_url=args.url,
    )
    print(
        "Rehearsal OK: "
        f"iterations={result.iterations}, "
        f"plans_checked={result.plans_checked}, "
        f"scripts_checked={result.scripts_checked}"
    )
    return 0


def cmd_export_plan_json(args: argparse.Namespace) -> int:
    profile = _load_profile_from_args(args)
    destinations = resolve_destinations(args.location)
    rng = random.Random(args.seed) if args.seed is not None else None
    plans = [build_input_plan(profile, destination, rng=rng).as_dict() for destination in destinations]
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(plan_summary_json(plans[0]) if len(plans) == 1 else str(plans), encoding="utf-8")
    print(f"Plan JSON written to {args.out}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="rolex-reservation-assistant")
    subparsers = parser.add_subparsers(dest="command", required=True)

    encrypt_parser = subparsers.add_parser("encrypt-profile")
    encrypt_parser.add_argument("--in", dest="input_path", required=True)
    encrypt_parser.add_argument("--out", dest="output_path", required=True)
    encrypt_parser.add_argument("--passphrase-env", default="APPLICANT_PROFILE_PASSPHRASE")
    encrypt_parser.set_defaults(func=cmd_encrypt_profile)

    valid_locations = ["all", *list_destination_keys()]
    plan_parser = subparsers.add_parser("plan")
    _add_profile_args(plan_parser)
    plan_parser.add_argument("--location", choices=valid_locations, default="all")
    plan_parser.add_argument("--deadline")
    plan_parser.add_argument("--audit-log")
    plan_parser.add_argument("--seed", type=int)
    plan_parser.set_defaults(func=cmd_plan)

    open_parser = subparsers.add_parser("open")
    _add_profile_args(open_parser)
    open_parser.add_argument("--location", choices=valid_locations, default="all")
    open_parser.add_argument("--interval-seconds", type=float, default=20.0)
    open_parser.add_argument("--audit-log")
    open_parser.add_argument("--seed", type=int)
    open_parser.set_defaults(func=cmd_open)

    cost_parser = subparsers.add_parser("captcha-cost")
    cost_parser.add_argument("--provider", default="enterprise-placeholder")
    cost_parser.add_argument("--expected-count", type=int, required=True)
    cost_parser.add_argument("--cost-per-1000", required=True)
    cost_parser.set_defaults(func=cmd_captcha_cost)

    e2e_parser = subparsers.add_parser("e2e-script")
    _add_profile_args(e2e_parser)
    e2e_parser.add_argument("--location", choices=list_destination_keys(), required=True)
    e2e_parser.add_argument("--url", required=True)
    e2e_parser.add_argument("--selectors", required=True)
    e2e_parser.add_argument("--out", required=True)
    e2e_parser.add_argument("--submit", action="store_true")
    e2e_parser.add_argument("--min-delay-ms", type=int, default=80)
    e2e_parser.add_argument("--max-delay-ms", type=int, default=220)
    e2e_parser.add_argument("--seed", type=int)
    e2e_parser.set_defaults(func=cmd_e2e_script)

    rehearse_parser = subparsers.add_parser("rehearse")
    _add_profile_args(rehearse_parser)
    rehearse_parser.add_argument("--location", choices=valid_locations, default="all")
    rehearse_parser.add_argument("--selectors", required=True)
    rehearse_parser.add_argument("--iterations", type=int, default=100)
    rehearse_parser.add_argument("--url", default="http://127.0.0.1:8765")
    rehearse_parser.set_defaults(func=cmd_rehearse)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.func(args))
    except Exception as exc:  # noqa: BLE001 - CLI should render friendly errors.
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
