from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from .guardrails import ensure_e2e_target_is_safe
from .input_plan import InputPlan, validate_input_plan


@dataclass(frozen=True)
class SelectorProfile:
    fields: dict[str, list[str]]
    submit_selectors: list[str]
    success_selectors: list[str]

    @classmethod
    def from_file(cls, path: str | Path) -> "SelectorProfile":
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        if not isinstance(data, dict) or not isinstance(data.get("fields"), dict):
            raise ValueError("Selector profile must contain a fields object")
        fields: dict[str, list[str]] = {}
        for key, value in data["fields"].items():
            if isinstance(value, str):
                fields[str(key)] = [value]
            elif isinstance(value, list) and all(isinstance(item, str) for item in value):
                fields[str(key)] = value
            else:
                raise ValueError("Each field selector must be a string or list of strings")
        submit_raw = data.get("submit_selector") or data.get("submit_selectors") or []
        success_raw = data.get("success_selector") or data.get("success_selectors") or []
        submit_selectors = _normalize_selector_list(submit_raw)
        success_selectors = _normalize_selector_list(success_raw)
        return cls(fields=fields, submit_selectors=submit_selectors, success_selectors=success_selectors)


def _normalize_selector_list(value: object) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return value
    if value in (None, []):
        return []
    raise ValueError("Selector list must be a string or list of strings")


def build_fill_payload(plan: InputPlan, selectors: SelectorProfile) -> dict[str, str]:
    validate_input_plan(plan)
    field_map = {field.key: field.value for field in plan.fields if field.value.strip()}
    return {key: field_map[key] for key in selectors.fields if key in field_map}


def build_playwright_script(
    plan: InputPlan,
    selectors: SelectorProfile,
    url: str,
    submit: bool,
    min_delay_ms: int = 80,
    max_delay_ms: int = 220,
) -> str:
    ensure_e2e_target_is_safe(url)
    if min_delay_ms < 0 or max_delay_ms < min_delay_ms:
        raise ValueError("Delay range must be non-negative and ordered")
    if submit and not selectors.submit_selectors:
        raise ValueError("submit=True requires at least one submit selector")
    payload = build_fill_payload(plan, selectors)
    script_data = {
        "url": url,
        "payload": payload,
        "selectors": selectors.fields,
        "submit_selectors": selectors.submit_selectors,
        "success_selectors": selectors.success_selectors,
        "submit": submit,
        "min_delay_ms": min_delay_ms,
        "max_delay_ms": max_delay_ms,
    }
    return _script_template(script_data)


def _script_template(script_data: dict[str, object]) -> str:
    data_literal = json.dumps(script_data, ensure_ascii=False, indent=2)
    return f'''# Generated by rolex-reservation-assistant. Local E2E targets only.
from __future__ import annotations

import random
from urllib.parse import urlparse

from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
from playwright.sync_api import sync_playwright

DATA = {data_literal}
LOCAL_HOSTS = {{"localhost", "127.0.0.1", "0.0.0.0", "::1"}}


def ensure_local_target(url: str) -> None:
    host = urlparse(url).hostname or ""
    if host not in LOCAL_HOSTS and not host.endswith(".localhost") and not host.endswith(".test"):
        raise RuntimeError("Generated E2E scripts are limited to local/test targets.")


def first_visible(page, selectors: list[str]):
    last_error = None
    for selector in selectors:
        try:
            locator = page.locator(selector).first
            locator.wait_for(state="visible", timeout=1500)
            return locator
        except PlaywrightTimeoutError as exc:
            last_error = exc
    raise RuntimeError(f"No visible selector found: {{selectors}}") from last_error


def fill_with_fallback(page, key: str, value: str, selectors: list[str]) -> None:
    locator = first_visible(page, selectors)
    locator.scroll_into_view_if_needed()
    locator.click()
    try:
        locator.fill("")
    except Exception:
        page.keyboard.press("Control+A")
        page.keyboard.press("Backspace")
    delay = random.randint(int(DATA["min_delay_ms"]), int(DATA["max_delay_ms"]))
    locator.type(value, delay=delay)
    actual = locator.input_value(timeout=1500)
    if actual != value:
        locator.fill(value)
        actual = locator.input_value(timeout=1500)
    if actual != value:
        raise RuntimeError(f"Field verification failed for {{key}}")


def main() -> None:
    ensure_local_target(str(DATA["url"]))
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(str(DATA["url"]), wait_until="domcontentloaded")
        for key, value in DATA["payload"].items():
            fill_with_fallback(page, key, str(value), DATA["selectors"][key])
        if DATA["submit"]:
            submit_button = first_visible(page, DATA["submit_selectors"])
            submit_button.scroll_into_view_if_needed()
            submit_button.click()
            for selector in DATA["success_selectors"]:
                try:
                    page.locator(selector).first.wait_for(state="visible", timeout=3000)
                    break
                except PlaywrightTimeoutError:
                    continue
            else:
                raise RuntimeError("Submit did not show a success marker")
        browser.close()


if __name__ == "__main__":
    main()
'''


def write_playwright_script(
    output_path: str | Path,
    plan: InputPlan,
    selectors: SelectorProfile,
    url: str,
    submit: bool,
    min_delay_ms: int = 80,
    max_delay_ms: int = 220,
) -> None:
    script = build_playwright_script(
        plan=plan,
        selectors=selectors,
        url=url,
        submit=submit,
        min_delay_ms=min_delay_ms,
        max_delay_ms=max_delay_ms,
    )
    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(script, encoding="utf-8")
